### ISSUE TITLE
[PHPUnit 10] Change setMethods() to onlyMethods()

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-phpunit#267]
See https://stackoverflow.com/questions/65075204/method-setmethods-is-deprecated-when-try-to-write-a-php-unit-test

**Comment by eerison** [comment]
yep it was deprecated in 9.x and already dropped in 10.x

https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

**Comment by eerison** [comment]
I'm on this issue ;)

**Comment by eerison** [comment]
Hey @TomasVotruba 

don't you think we could add this into `PhpUnit90` rules insteadof `PhpUnit10`?

**Comment by TomasVotruba** [comment]
Hey, we usually add the rule when the change will affect users. When people upgrade to PHPUnit 9.0 and this change is not there yet, it would break.

So PHPUnit 10.0 is safer

**Comment by eerison** [comment]
It does not work for setMethods :'(

https://github.com/rectorphp/rector-phpunit/commit/6d9316d7c1c4ba206fe7904adfeb03521f26cc2b

**Comment by eerison** [comment]
it works just in the first case


```php
        //first
        $this->setMethods();

        //second
        $contractMock = $this->getMockBuilder(Contract::class)
            ->disableOriginalConstructor()
            ->setMethods(['getCancelledAt', 'terminate'])
            ->getMock();
```

**Comment by samsonasik** [comment]
I am on mobile, `disableOriginalConstructor()` seems return different instance?

**Comment by eerison** [comment]
> I am on mobile, `disableOriginalConstructor()` seems return different instance?

I see the issue, I will provide a PR for this

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-phpunit/pull/280

**Comment by eerison** [comment]
I was wondering why this issue wasn't close in the first PR, maybe you have the feling that it wasn't fixed 😄 

Just to confirm that it worked <3
